### ISSUE TITLE
Logic bug - fails to install deno [WARN] Failed to downloading Deno binary file, fallback to build from source

### ISSUE THREAD

**Issue by PaulThompson** [ghosind/dvm#26]
**Describe the bug**
Error installing deno from dvm v0.8.0

It hits `[WARN] Failed to downloading Deno binary file, fallback to build from source.`
I don't want to install from source and don't have `rustc` installed on this box.
Then it hits the error from `rustc` not installed.

**To Reproduce**
Occurs on v0.8.0 or later.
Does not occur for v0.7.3

**Additional context**

I bisected the git commits and traced the likely cause to commit `bb103932e3378fb4be8f6b0015b9e5cd2feef587`
```
-    if ! dvm_extract_file "$version"
-    then
-      return
-    fi
-
-    dvm_print "Deno $version has installed."
-
-    dvm_use_version "$version"
-    dvm_set_default_alias_after_install "$version"
+    ! dvm_extract_file "$version"
```
https://github.com/ghosind/dvm/blob/bb103932e3378fb4be8f6b0015b9e5cd2feef587/dvm.sh#L1056

That line should probably be `dvm_extract_file "$version"` and not inverted with `!`

Opened PR https://github.com/ghosind/dvm/pull/25

**Comment by ghosind** [comment]
Hi Paul,

Thank you for your issue about this problem.

For v0.8.x, I have added the feature that installs deno from the source, and It is a default behavior that executes after failing to install the binary file. It's my mistake, maybe most people don't want to install from source and I'll update it soon.
