### ISSUE TITLE
`dvm use` where `.dvmrc` requires a non-installed version - help is shown but no error is reported

### ISSUE THREAD

**Issue by paul-thompson-helix** [ghosind/dvm#3]
Setup:
* Create `.dvmrc` file with a version that isn't installed yet: `echo v1.8.0 > .dvmrc`
* Run `dvm use`

Expected:  An error eg: 1.8.0 is not installed yet - please install using `dvm install`

Actual: `dvm help` is shown.

**Comment by ghosind** [comment]
Hi Paul,

**Comment by ghosind** [comment]
Hi Paul,

Thank you for your reporting, I'll fix this bug and publish a new version.
