### ISSUE TITLE
Choose deno versions by manipulating PATH rather than symlinking?

### ISSUE THREAD

**Issue by paul-thompson-helix** [ghosind/dvm#4]
It would be great if this tool implemented the choice of deno binary by setting PATH rather than symlinking.

That way the choice of deno version would be isolated to the process and it's children.
One could have two different deno versions in use in two different shells.

Currently the choice in one shell can be changed by another shell.

It would also be good to be able to run
`which deno`
and have it report:
`~/.dvm/versions/xxx/deno`

(Similar to how nvm works)

Any suggestions or PR welcome on this?

**Comment by ghosind** [comment]
Yes, PATH is better than symbolic link.

I had thought use PATH when I implement `use` command, but symlink is easy to implement and I can make it fastly. However, I also think it's better to replace it with PATH in future versions.

**Comment by paul-thompson-helix** [comment]
Excellent - here's a PR for it: https://github.com/ghosind/dvm/pull/5

**Comment by ghosind** [comment]
Thx and your work are very cool.

I have tested it on my local computer, and it works great.

But, I found some problems with other commands (like `ls`, `current`), their implementations may also need to change later.
