### ISSUE TITLE
`dvm_success` and `dvm_failure` were not working

### ISSUE THREAD

**Issue by ghosind** [ghosind/dvm#9]

**Comment by paul-thompson-helix** [comment]
What's wrong?

**Comment by ghosind** [comment]
I have tested it on my mac (zsh) and centos (bash), and these functions cannot stop the program in both environments.

for example, it will print the following text if I run it without any parameters.

```
$ dvm

Deno Version Manager
Usage:
# ...

[ERR] unknown command .

Deno Version Manager
Usage:
# ...
```

for this case, the program should exit after printing the first help message

**Comment by ghosind** [comment]
I have tested it on my mac (zsh) and centos (bash), and these functions cannot stop the program in both environments.

for example, it will print the following text if I run it without any parameters.

```
$ dvm

Deno Version Manager
Usage:
# ...

[ERR] unknown command .

Deno Version Manager
Usage:
# ...
```

for this case, the program should exit after printing the first help message
